name = "WrapR"
uuid = "2cb1610a-c9de-4cc5-9cd8-c4853e5c0aaf"
authors = ["Albert Zevelev"]
version = "0.1"

[deps]
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"

[compat]
RCall = ">= 0.13"
julia = ">= 1.5"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
